config/routes.rb
Rails.application.routes.draw do


#  post ':user_id'
 post '/place_order', to:'checkout#place_order',as: 'place_order'
 get '/checkout', to:'checkout#display_checkout', as: 'checkout'

  get '/remove_from_cart/:meal_id', to: 'shopping_cart#remove'
  get '/cart', to:'shopping_cart#display_cart'
  get '/shopping_cart/:meal/', to: 'shopping_cart#add_to_cart', as:'shopping_cart'
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'log_in', to: 'sessions#new', as: 'log_in'
  resources :sessions

  get '/sign_up', to: 'customers#new'
  resources :customers

 get '/sign_in', to: 'home#sign_in'
 get '/category/search/:number', to: 'search#category_result'

  get '/product', to: 'home#get_product'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  get 'search/keyword_result/', to: 'search#keyword_result'

  get 'category/display_category/:value', to: 'category#display_category'


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'admin/meals/delete/remove/:value', to: 'delete#remove_image'
  #get 'category/meat',to:'category#display_meat'
  root'home#index'
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
# Admin Model
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# Categoty Model
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
# Customer Mode
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :province
  validates :full_name, :address, :city, :email, presence: true
  validates :user_name, uniqueness: true
  # validates :password, length: { minimum: 6 }
  validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}
  attr_accessor :password
  before_save :encrypted_password
  validates_confirmation_of :password

  def self.authenticate(email, password)
    user = find_by(email: email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypted_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
    end
  end
end

app/models/meal.rb
# Meal Mode
class Meal < ApplicationRecord
  belongs_to :category
  has_attached_file :image,
                    # url: ':rails_root/app/assets/images/:basename.:extension'
                    path: ':rails_root/app/assets/images/:basename.:extension',
                    styles: { small: '259 x 194<' }
  validates :description, :price, presence: true
  validates :price, numericality: { only_integer: true }
  monetize :cost_cents

  validates_attachment_content_type :image, content_type: ['image/jpg',
                                                           'image/jpeg',
                                                           'image/png',
                                                           'image/gif']

  # Displays the description column name of a meal in the timeoutable
  # Used especially because i have a column name called description
  # and not name
  def name
    title
  end
end

app/models/order.rb
# The Order Model
class Order < ApplicationRecord
  belongs_to :customer
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/delete_helper.rb
module DeleteHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meat_helper.rb
module MeatHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodShare</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/navbar/_category_search.slim
nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  button.navbar-toggler.navbar-toggler-right aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  a.navbar-brand href="/"  Home
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        a.nav-link href="/"
          | Home
          span.sr-only (current)
      li.nav-item
        a.nav-link href='/about' About
      li.nav-item
        a.nav-link href="/contact"  Contact
    form.form-inline.my-2.my-lg-0 action= "/category/search/#{params[:value]}"
      input.form-control.mr-sm-2 placeholder="Search" type="text" name="search_value" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search

app/views/navbar/_navbar.slim
nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  button.navbar-toggler.navbar-toggler-right aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  a.navbar-brand href="/"  Home
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        a.nav-link href="/" 
          | Home
          span.sr-only (current)
      li.nav-item
        a.nav-link href='/about' About
      li.nav-item
        a.nav-link href="/contact"  Contact
      li.nav-item
      - if current_user
        | Logged in as #{current_user.email}.
        =  link_to "Log out", log_out_path
        
      - else
        = link_to "Sign up", sign_up_path
        | or
        = link_to "log in ", log_in_path
        
      li.nav-item
        a.nav-link href='/cart' Cart 
      li.nav-item
        a.nav-link href='/checkout' Checkout 
    form.form-inline.my-2.my-lg-0 action="/search/keyword_result/"
      input.form-control.mr-sm-2 placeholder="Search" type="text" name="search_value" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search